# Generated by Django 5.1.7 on 2025-03-09 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(default='AH001', max_length=5, primary_key=True, serialize=False, unique=True)),
                ('artist_lname', models.CharField(blank=True, max_length=50, null=True)),
                ('artist_fname', models.CharField(blank=True, max_length=50, null=True)),
                ('artist_site', models.CharField(blank=True, max_length=100, null=True)),
                ('artist_email', models.CharField(blank=True, max_length=100, null=True)),
                ('artist_bio', models.CharField(blank=True, max_length=800, null=True)),
                ('artist_phone', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('storage_id', models.CharField(default='W000000', max_length=7, primary_key=True, serialize=False, unique=True)),
                ('storage_loc', models.CharField(blank=True, max_length=40, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'storage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FlatFile',
            fields=[
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.storage')),
                ('letter_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'flat_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rack', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.storage')),
            ],
            options={
                'db_table': 'rack',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WallSpace',
            fields=[
                ('wall', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='website.storage')),
            ],
            options={
                'db_table': 'wall_space',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('art_num', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('art_title', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('art_medium', models.CharField(blank=True, max_length=50, null=True)),
                ('is_sold', models.CharField(blank=True, max_length=1, null=True)),
                ('art_size', models.CharField(blank=True, max_length=50, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.artist')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.storage')),
            ],
            options={
                'db_table': 'artwork',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('art_num', models.ForeignKey(blank=True, db_column='art_num', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.artwork')),
            ],
            options={
                'db_table': 'sale',
                'managed': True,
            },
        ),
    ]
