# Generated by Django 5.1.7 on 2025-03-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='storage_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
