# Generated by Django 5.1.7 on 2025-03-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_storage_storage_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='on_loan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
