# Generated by Django 5.1.7 on 2025-03-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_storage_on_loan_storage_storage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='rack_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
