# Generated by Django 5.1.7 on 2025-03-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rack_rack_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
